export { default as Hero } from './hero/Hero'
export { default as About } from './about/About'
export { default as MenuIntro } from './menuIntro/MenuIntro'
export { default as Carousel } from './carousel/Carousel'
export { default as TextAnimation } from './carousel/TextAnimation'
