export { default as img1 } from './images/img1.jpg';
export { default as img2 } from './images/img2.jpg';
export { default as img3 } from './images/img3.jpg';
export { default as img4 } from './images/img4.jpg';
export { default as img5 } from './images/img5.jpg';
export { default as img6 } from './images/img6.jpg';
export { default as img7 } from './images/img7.jpg';
export { default as img8 } from './images/img8.jpg';
export { default as img9 } from './images/img9.jpg';